# test1.c

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class CustomLayer(nn.Module):
    def __init__(self, weights, biases):
        super(CustomLayer, self).__init__()
        self.weights = nn.Parameter(weights)
        self.biases = nn.Parameter(biases)

    def forward(self, x):
        return F.linear(x, self.weights, self.biases)

def relu_layer(layer, input_tensor):
    return F.relu(layer(input_tensor))

def ces_layer(layer, input_tensor, target):
    logits = layer(input_tensor)
    probs = F.softmax(logits, dim=0)
    loss = F.cross_entropy(logits.unsqueeze(0), target.unsqueeze(0))  # cross_entropy also does softmax
    return probs, loss

input_tensor = torch.tensor([0.5, 0.75])
target_tensor = torch.tensor([0.0, 1.0])

layer1 = CustomLayer(
    torch.tensor([[0.5, 0.3], [0.2, 0.1], [0.7, 0.9]]),
    torch.tensor([0.0, 0.0, 0.0])
)

layer2 = CustomLayer(
    torch.tensor([[0.5, 0.3, 0.2], [0.1, 0.7, 0.9]]),
    torch.tensor([0.0, 0.0])
) 

x2 = relu_layer(layer1, input_tensor)
probs, loss = ces_layer(layer2, x2, target_tensor)
loss.backward()


print("layer1 output:")
print(x2)
print()
print("probs:")
print(probs)
print()
print(f"Cross entropy error: {loss.item()}")
print()

print("layer1 grad:")
print(layer1.weights.grad)
print(layer1.biases.grad)
print()
print("layer2 grad:")
print(layer2.weights.grad)
print(layer2.biases.grad)
print()

layer1 output:
tensor([0.4750, 0.1750, 1.0250], grad_fn=<ReluBackward0>)

probs:
tensor([0.3549, 0.6451], grad_fn=<SoftmaxBackward0>)

Cross entropy error: 0.4383745491504669

layer1 grad:
tensor([[ 0.0710,  0.1065],
        [-0.0710, -0.1065],
        [-0.1242, -0.1863]])
tensor([ 0.1420, -0.1420, -0.2484])

layer2 grad:
tensor([[ 0.1686,  0.0621,  0.3638],
        [-0.1686, -0.0621, -0.3638]])
tensor([ 0.3549, -0.3549])



In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class CustomLayer(nn.Module):
    def __init__(self, weights, biases):
        super(CustomLayer, self).__init__()
        self.weights = nn.Parameter(weights)
        self.biases = nn.Parameter(biases)

    def forward(self, x):
        return F.linear(x, self.weights, self.biases)

def relu_layer(layer, input_tensor):
    return F.relu(layer(input_tensor))

def ces_layer(layer, input_tensor, target):
    logits = layer(input_tensor)
    probs = F.softmax(logits, dim=0)
    loss = F.cross_entropy(logits.unsqueeze(0), target.unsqueeze(0))  # cross_entropy also does softmax
    return probs, loss

input_tensor = torch.tensor([[0.35, -0.65], [-0.8, 0.45]])
target_tensor = torch.tensor([[0.1, -0.9], [-0.9, 0.1]])

layer1 = CustomLayer(
    torch.tensor([[-0.25, 0.45], [0.55, -0.15], [0.85, -0.75]]),
    torch.tensor([0.05, -0.1, 0.05])
)

layer2 = CustomLayer(
    torch.tensor([[0.35, -0.25, 0.15], [-0.05, 0.85, -0.75]]),
    torch.tensor([0.05, -0.1])
)

x2 = relu_layer(layer1, input_tensor)
probs, loss = ces_layer(layer2, x2, target_tensor)
loss.backward()


print("layer1 output:")
print(x2)
print()
print("probs:")
print(probs)
print()
print(f"Cross entropy error: {loss.item()}")
print()

print("layer1 grad:")
print(layer1.weights.grad)
print(layer1.biases.grad)
print()
print("layer2 grad:")
print(layer2.weights.grad)
print(layer2.biases.grad)
print()

layer1 output:
tensor([[0.0000, 0.1900, 0.8350],
        [0.4525, 0.0000, 0.0000]], grad_fn=<ReluBackward0>)

probs:
tensor([[0.4799, 0.3912],
        [0.5201, 0.6088]], grad_fn=<SoftmaxBackward0>)

Cross entropy error: -0.6549127101898193

layer1 grad:
tensor([[-0.0795,  0.0447],
        [ 0.1085, -0.2015],
        [-0.0897,  0.1667]])
tensor([ 0.0994,  0.3100, -0.2564])

layer2 grad:
tensor([[ 0.1095, -0.0460, -0.2020],
        [-0.1328,  0.0558,  0.2451]])
tensor([0., 0.])

